package e

var MsgFlags = map[int]string{
	SUCCESS:        "ok",
	ERROR:          "fail",
	INVALID_PARAMS: "參數錯誤",
	INVALID_JWT:    "Token未帶入",

	ERROR_AUTH_CHECK_TOKEN_FAIL:    "token 驗證失敗",
	ERROR_AUTH_CHECK_TOKEN_FORMAT:  "token 格式錯誤",
	ERROR_AUTH_CHECK_TOKEN_TIMEOUT: "token 已超時",
	ERROR_AUTH_CREATE_TOKEN:        "token 生成失敗",
	ERROR_AUTH:                     "token 不可用",
	ERROR_AUTH_CHECK_USELESS:       "token 無效",
	ERROR_ADDRESS_NOTFOUND:         "該地址不存在",
	ERROR_GET_PARAMS:               "取得參數失敗",
	PARAMETER_ERROR:                "請求參數錯誤",
	VERIFYEMAILEXPTIMESUP:          "驗證碼時效已過",
	NAME_EXISTED:                   "名稱已存在",
	DB_INPUT_FAIL:                  "資料寫入失敗",
	DB_OUTPUT_FAIL:                 "資料讀取失敗",
	NO_HAVE_DATA:                   "查無資料",
	KYC_NOT_IN_PROGRESS:            "此會員尚未提交KYC資料",
	EMAIL_SEND_ERROR:               "email 發送失敗",
	USER_UPDATE_ERROR:              "更新使用者資訊失敗",
	USER_CREATE_ERROR:              "建立使用者資訊失敗",
	WALLECT_NOT_EXIST:              "使用者錢包不存在",
	PACKAGE_CANNOT_OPEN:            "卡包鎖定中",
	NOT_PRODUCT_OWNER:              "非卡包持有者",
	PRODUCT_NOT_EXIST:              "卡包不存在",
	PRODUCT_HAVE_OWNER:             "卡包已發出",
	EMAIL_TRY_LATTER:               "請於一分鐘後重新發送驗證碼",

	ERROR_2FA_VERIFY:       "驗證碼輸入錯誤",
	ERROR_2FA_OPEN_ALREADY: "已開通過2FA",
	ERROR_2FA_NOT_OPEN_YET: "未開通2FA",
	EMAIL_ALREADY_EXIST:    "信箱已被使用",

	ACTIVITY_NOT_FOUND:                  "沒有此集章活動",
	ERROR_QRCODE_NO_ACTIVITY:            "沒有該活動",
	ERROR_QRCODE_ACCOUNT_NO_SERIAL:      "該帳號沒有此序號",
	ERROR_QRCODE_ACTIVITY_NO_SERIAL:     "該活動沒有此序號",
	ERROR_QRCODE_ACTIVITY_NOT_START:     "活動尚未開始",
	ERROR_QRCODE_ACTIVITY_NOT_AVAILABLE: "活動已結束",
	ERROR_QRCODE_SERIAL_USED_ALREADY:    "序號已使用",
	ERROR_QRCODE_SERIAL_NOT_BINDED:      "序號未註冊",
	ERROR_QRCODE_REPEAT_GROUP:           "有大於一個相同的序號在同組活動群組，請通知 Jcard 調整該序號",
	ERROR_QRCODE_FIRM:                   "該帳號無核銷權限",
	UPDATE_QRCODE_SUCCESS:               "兌換成功",
	UPDATE_QRCODE_FAIL:                  "兌換失敗，請洽管理員",

	EMAIL_SEND_SUCCESS: "email 發送成功",
	UNAUTHORIZED:       "驗證失敗",
	JWT_EXPIRED:        "token 已過期",

	ERROR_SEAL_NFT_SOLD_OUT:  "此 NFT 已兌換完畢",
	ERROR_CODE_NFT_SEARCH:    "此兌換碼無可換的 NFT",
	ERROR_DB_SEARCH:          "資料庫查詢失敗",
	ERROR_USER_NOT_FOUND:     "此會員不存在",
	USER_CHANGE_BEFORE:       "已兌換過此 NFT",
	USER_AMOUNT_NO_ENOUGHT:   "持有數量不足",
	ERROR_USER_ANSWER_BEFORE: "此會員已作答過",
	ERROR_USER_ANSWER_COUNT:  "作答數量與題目數量不符",
	QUESTION_EXIST:           "此語言題目已經建立",
	ERROR_IMAGE_CONTENT_TYPE: "請上傳 png 或 jpeg 格式",
	OPTION_EXIST:             "此選項已存在",
	THEME_IN_USED:            "該活動使用中",
	PRODUCTHAVETOKEN:         "此卡片已被放入卡包",
	VOTED_TODAY:              "今天已經投過票了",
	//融合
	NOT_TOKEN_OWNER:         "非 NTF 持有者",
	MIXFAIL:                 "合成失敗",
	MIXSUCCESS:              "合成成功",
	MIXNOTENOUGH:            "合成卡數量不足",
	MIXMATERIALERROR:        "合成素材ID與主卡不符",
	MATERIAL_NOT_FOUND:      "未找到融合素材",
	EMAIL_VERIFY_CODE_ERROR: "驗證碼錯誤",
	TOOMANYREQ:              "請求次數過多",
	MIX_ALREADY:             "已融合過該卡片",

	ACCOUNT_NOT_EXIST:              "帳號未註冊",
	PASSWORD_NOT_CORRECT:           "密碼錯誤",
	EMAIL_CREATE_BY_META:           "此帳號已用 Meta 快速註冊",
	EMAIL_CREATE_BY_GOOGLE:         "此帳號已用 Google 快速註冊",
	EMAIL_CREATED:                  "此信箱已用一般註冊",
	EMAIL_NOT_FOUND:                "此信箱尚未註冊",
	CALLAPIERROR:                   "呼叫 api 錯誤",
	UPLOAD_FILE_ERROR:              "上傳檔案失敗",
	UPLOAD_FILE_NOT_MATCH:          "上傳檔案與檔名數量不符",
	CONTRACT_ID_DUPLICATE:          "合約 id  重複",
	CONTRACT_SYMBOL_DUPLICATE:      "合約 symbol 重複",
	CONTRACT_NOTFOUND:              "未找到此合約",
	MINT_TOKEN_ERROR:               "鑄造失敗",
	MINT_OUTOFLIMIT:                "鑄造數量大於設定數量",
	IMAGE_IS_NULL:                  "圖片未帶入",
	IMAGE_NOT_MATCHL:               "圖片數量與鑄造數量不符",
	PRODUCT_ID_DUPLICATE:           "商品 id 重複",
	USER_ADDRESS:                   "使用者錢包查詢",
	USER_TOKEN:                     "使用者Token查詢",
	NICKNAME_ALREADY_EXIST:         "暱稱已被使用",
	ACCOUNT_ALREADY_EXIST:          "帳號已被使用",
	FIRM_NOT_EXIST:                 "未找到該廠商",
	FIRM_NOT_OPEN:                  "廠商未開通，請聯絡管理員",
	VOUCHER_IS_USED:                "兌換碼已有使用紀錄",
	MIX_ACTIVITY_USED:              "卡包已在融合活動設定",
	SEEAL_ACTIVITY_USED:            "卡包已在集章活動設定",
	REDEMPTION_ACTIVITY_USED:       "卡包已在兌換碼設定",
	SEAL_CHANGE_ACTIVITY_USED:      "卡包已在集章後兌換設定",
	SURVEY_ACTIVITY_USED:           "卡包已在測驗活動設定",
	PRODUCT_LANGUAGE_ALREADY_EXIST: "卡包語系已存在",
	APPLY_WITHDRAW_BEFORE:          "此 NFT 已申請",
	NO_DATA_UPDATED:                "無資料更新",
	NO_UPDATE_SURVEY_ACTIVITY:      "測驗基本資訊無更新",
	NO_UPDATE_SURVEY_INTRODUCTION:  "測驗多國資訊無更新",
	NO_UPDATE_SURVEY_ALL:           "測驗基礎和多國資訊無更新",
	NO_UPDATE_SURVEY_QUESTION:      "測驗題目無更新",
	NO_UPDATE_SURVEY_OPTION:        "測驗選項無更新",
	NO_UPDATE_SURVEY_PRIZE:         "測驗答案無更新",
	WRONG_ANSWER:                   "回答與正確答案不符",
	NO_UPDATE_MIX_ACTIVITY:         "融合活動資訊無更新",
	NO_UPDATE_MIX_INTRODUCTION:     "融合活動多國無更新",
	NO_UPDATE_MIX_ALL:              "融合活動和多國資訊無更新",
	PROFILE_IS_NOT_COMPLETE:        "個人頁面的資料需填寫完成，才可兌換此活動集張。",
	EMAIL_NOT_RECEIVED:             "未收到 email",
	EXCEED_SEAL_DISTANCE:           "超過可集章距離",
	CITY_CARD_FAILED:               "取得市民卡資料錯誤",
	EMAIL_CREATE_BY_CITYCARD:       "此帳號已用桃園市民卡快速註冊",
	EMAIL_NOT_ALLOW:                "email 格式錯誤",
	CITYCARD_BIND_BEFORE:           "此市民卡已綁訂",
	CITYCARD_ADD_EMAIL:             "請於市民卡新增 Email 繼續綁定",
	TAOYUAN_ADD_EMAIL:              "請新增 Email 繼續綁定",
	SMS_SEND_FAIL:                  "簡訊發送失敗",
	PHONE_USED_GOOGLE:              "此手機號碼已用 Google 快速註冊",
	PHONE_USED_META:                "此手機號碼已用 Meta 快速註冊",
	PHONE_USED_REGISTRATION:        "此手機號碼已用於 email 一般註冊",
	PHONE_USED_SMS:                 "此手機號碼已用手機簡訊註冊",
	PHONE_FORMAT_ERROR:             "手機格式錯誤",
	PHONE_ALREADY_USED:             "此手機號碼已被使用",
	ACCOUNT_NOT_VERIFIED:           "帳號未驗證",
	EMAIL_NOT_MATCH:                "email 不符合",
	SEAL_COLLECTOR_LOCKED:          "此集章序號正在處理中，請稍後再試",
	EMAIL_LOCKED:                   "驗證碼發送超過 3 次，請 1 小時後再嘗試",
	PHONE_DAY_LIMIT:                "手機號碼今日註冊次數已達上限，請明日再嘗試",
	PHONE_NOT_MATCH:                "手機號碼不符合",
	AMOUNT_DISMATCH:                "資料數量不符合",

	//上鏈
	ONCHAINFAIL:                        "上鏈失敗",
	TOKEN_AND_PRODUCT_NUMBER_DIFFERENR: "卡片與卡包數量不符合",
}

func GetMsg(code int) string {
	msg, ok := MsgFlags[code]
	if ok {
		return msg
	}

	return MsgFlags[ERROR]
}
