"""initial_database_schema_v0_2

Revision ID: 23aaa1ac9d45
Revises: flex_msg_001
Create Date: 2025-11-11 17:58:22.687840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23aaa1ac9d45'
down_revision: Union[str, None] = 'flex_msg_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('campaign_name', sa.String(length=100), nullable=False, comment='活動名稱'),
    sa.Column('campaign_tag', sa.String(length=50), nullable=True, comment='活動標籤'),
    sa.Column('campaign_date', sa.Date(), nullable=True, comment='活動日期'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='活動開始日期'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='活動結束日期'),
    sa.Column('description', sa.Text(), nullable=True, comment='活動描述'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='活動狀態：active/inactive/completed'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interaction_tags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tag_name', sa.String(length=20), nullable=False, comment='標籤名稱'),
    sa.Column('tag_source', sa.String(length=20), nullable=True, comment='標籤來源：訊息模板/問券模板'),
    sa.Column('trigger_count', sa.Integer(), nullable=True, comment='觸發次數'),
    sa.Column('trigger_member_count', sa.Integer(), nullable=True, comment='觸發會員數'),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True, comment='最近觸發時間'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_tags_tag_name'), 'interaction_tags', ['tag_name'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('line_uid', sa.String(length=100), nullable=True, comment='LINE UID'),
    sa.Column('line_avatar', sa.String(length=500), nullable=True, comment='LINE 頭像 URL'),
    sa.Column('line_name', sa.String(length=100), nullable=True, comment='LINE 顯示名稱'),
    sa.Column('name', sa.String(length=32), nullable=True, comment='會員姓名（統一單欄位）'),
    sa.Column('gender', sa.String(length=1), nullable=True, comment='性別：0=不透漏/1=男/2=女'),
    sa.Column('birthday', sa.Date(), nullable=True, comment='生日'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='電子信箱'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手機號碼'),
    sa.Column('id_number', sa.String(length=50), nullable=True, comment='身分證/護照號碼'),
    sa.Column('residence', sa.String(length=100), nullable=True, comment='居住地'),
    sa.Column('join_source', sa.String(length=20), nullable=False, comment='加入來源：LINE/CRM/PMS/ERP/系統'),
    sa.Column('receive_notification', sa.Boolean(), nullable=True, comment='是否接收優惠通知'),
    sa.Column('internal_note', sa.Text(), nullable=True, comment='內部備註'),
    sa.Column('last_interaction_at', sa.DateTime(), nullable=True, comment='最後互動時間'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_email'), 'members', ['email'], unique=False)
    op.create_index(op.f('ix_members_id_number'), 'members', ['id_number'], unique=True)
    op.create_index(op.f('ix_members_line_uid'), 'members', ['line_uid'], unique=True)
    op.create_index(op.f('ix_members_phone'), 'members', ['phone'], unique=False)
    op.create_table('ryan_click_demo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('line_id', sa.String(length=64), nullable=False, comment='LINE 用戶 UID'),
    sa.Column('source_campaign_id', sa.Integer(), nullable=False, comment='來源活動 ID'),
    sa.Column('line_display_name', sa.String(length=128), nullable=True, comment='LINE 顯示名稱'),
    sa.Column('total_clicks', sa.Integer(), nullable=False, comment='總點擊次數'),
    sa.Column('last_clicked_at', sa.DateTime(), nullable=True, comment='最後點擊時間'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新時間'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_id', 'source_campaign_id', name='uq_line_source_campaign')
    )
    op.create_index(op.f('ix_ryan_click_demo_source_campaign_id'), 'ryan_click_demo', ['source_campaign_id'], unique=False)
    op.create_table('survey_templates',
    sa.Column('name', sa.String(length=100), nullable=False, comment='範本名稱'),
    sa.Column('description', sa.Text(), nullable=True, comment='範本描述'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='範本圖標'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='範本類別'),
    sa.Column('default_questions', sa.JSON(), nullable=True, comment='預設題目'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否啟用'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主鍵ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='創建時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False, comment='用戶名'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='郵箱'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密碼雜湊'),
    sa.Column('full_name', sa.String(length=100), nullable=True, comment='全名'),
    sa.Column('role', sa.Enum('ADMIN', 'MARKETING', 'CUSTOMER_SERVICE', name='userrole'), nullable=False, comment='角色'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否啟用'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最後登入時間'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主鍵ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='創建時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('message_templates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True, comment='模板名稱'),
    sa.Column('template_type', sa.String(length=20), nullable=True, comment='模板類型：Template01/Template02/Template03/Template04'),
    sa.Column('text_content', sa.Text(), nullable=True, comment='文字內容'),
    sa.Column('image_url', sa.String(length=500), nullable=True, comment='圖片 URL'),
    sa.Column('title', sa.String(length=100), nullable=True, comment='標題'),
    sa.Column('description', sa.Text(), nullable=True, comment='內文描述'),
    sa.Column('amount', sa.Integer(), nullable=True, comment='金額數值'),
    sa.Column('button_text', sa.String(length=50), nullable=True, comment='按鈕文字'),
    sa.Column('button_count', sa.Integer(), nullable=True, comment='顯示的文字按鈕數量'),
    sa.Column('buttons', sa.JSON(), nullable=True, comment='按鈕配置（JSON）'),
    sa.Column('interaction_tag', sa.String(length=50), nullable=True, comment='互動標籤'),
    sa.Column('interaction_tag_id', sa.BigInteger(), nullable=True),
    sa.Column('interaction_result', sa.JSON(), nullable=True, comment='互動結果配置'),
    sa.Column('action_type', sa.String(length=20), nullable=True, comment='動作按鈕互動類型：開啟網址/觸發文字/觸發圖片'),
    sa.Column('action_url', sa.String(length=500), nullable=True, comment='URL 網址'),
    sa.Column('action_text', sa.Text(), nullable=True, comment='觸發的訊息文字'),
    sa.Column('action_image', sa.String(length=500), nullable=True, comment='觸發的圖片檔案'),
    sa.Column('notification_text', sa.String(length=100), nullable=True, comment='通知訊息'),
    sa.Column('preview_text', sa.String(length=100), nullable=True, comment='訊息預覽'),
    sa.Column('carousel_count', sa.Integer(), nullable=True, comment='輪播圖卡數量（2-9張）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.ForeignKeyConstraint(['interaction_tag_id'], ['interaction_tags.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pms_integrations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_number', sa.String(length=50), nullable=True, comment='身分證字號'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手機號碼'),
    sa.Column('stay_records', sa.JSON(), nullable=True, comment='住宿紀錄資訊（JSON格式）'),
    sa.Column('room_type', sa.String(length=50), nullable=True, comment='房型'),
    sa.Column('stay_date', sa.Date(), nullable=True, comment='住宿日期'),
    sa.Column('member_id', sa.BigInteger(), nullable=True, comment='關聯的會員ID'),
    sa.Column('match_status', sa.String(length=20), nullable=True, comment='比對狀態：matched/pending/failed'),
    sa.Column('match_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='比對成功率'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='比對失敗原因'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pms_integrations_id_number'), 'pms_integrations', ['id_number'], unique=False)
    op.create_index(op.f('ix_pms_integrations_member_id'), 'pms_integrations', ['member_id'], unique=False)
    op.create_index(op.f('ix_pms_integrations_phone'), 'pms_integrations', ['phone'], unique=False)
    op.create_table('surveys',
    sa.Column('name', sa.String(length=200), nullable=False, comment='問卷名稱'),
    sa.Column('template_id', sa.BigInteger(), nullable=False, comment='範本ID'),
    sa.Column('description', sa.Text(), nullable=True, comment='問卷描述'),
    sa.Column('target_audience', sa.Enum('ALL', 'FILTERED', name='targetaudience'), nullable=False, comment='目標受眾'),
    sa.Column('target_tags', sa.JSON(), nullable=True, comment='目標標籤'),
    sa.Column('schedule_type', sa.Enum('IMMEDIATE', 'SCHEDULED', name='scheduletype'), nullable=False, comment='排程類型'),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True, comment='排程時間'),
    sa.Column('sent_at', sa.DateTime(), nullable=True, comment='實際發送時間'),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'published', name='surveystatus', native_enum=False, length=20), nullable=False, comment='狀態'),
    sa.Column('response_count', sa.Integer(), nullable=True, comment='回應數'),
    sa.Column('view_count', sa.Integer(), nullable=True, comment='瀏覽數'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='創建者ID'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主鍵ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='創建時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['survey_templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auto_responses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True, comment='自動回應名稱'),
    sa.Column('trigger_type', sa.String(length=20), nullable=False, comment='觸發類型：新好友歡迎訊息/關鍵字觸發/指定時間觸發'),
    sa.Column('content', sa.Text(), nullable=False, comment='回應內容'),
    sa.Column('template_id', sa.BigInteger(), nullable=True, comment='模板ID'),
    sa.Column('keywords', sa.JSON(), nullable=True, comment='關鍵字（JSON格式，最多20組）'),
    sa.Column('trigger_time_start', sa.Time(), nullable=True, comment='指定時間區間起始'),
    sa.Column('trigger_time_end', sa.Time(), nullable=True, comment='指定時間區間結束'),
    sa.Column('date_range_start', sa.Date(), nullable=True, comment='指定日期區間起始'),
    sa.Column('date_range_end', sa.Date(), nullable=True, comment='指定日期區間結束'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='啟用狀態'),
    sa.Column('response_count', sa.Integer(), nullable=True, comment='自動回應訊息數量（1-5筆）'),
    sa.Column('trigger_count', sa.Integer(), nullable=True, comment='觸發次數'),
    sa.Column('success_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='發送成功率'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.ForeignKeyConstraint(['template_id'], ['message_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consumption_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False, comment='所屬會員ID'),
    sa.Column('pms_integration_id', sa.BigInteger(), nullable=True, comment='PMS整合資料ID'),
    sa.Column('consumption_time', sa.DateTime(), nullable=True, comment='消費時間'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True, comment='消費金額'),
    sa.Column('room_type', sa.String(length=50), nullable=True, comment='房型或套餐'),
    sa.Column('stay_duration', sa.Integer(), nullable=True, comment='住宿天數'),
    sa.Column('notes', sa.Text(), nullable=True, comment='備註'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pms_integration_id'], ['pms_integrations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumption_records_member_id'), 'consumption_records', ['member_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.BigInteger(), nullable=False, comment='訊息模板ID'),
    sa.Column('message_content', sa.Text(), nullable=True, comment='訊息內容（用於列表顯示）'),
    sa.Column('thumbnail', sa.String(length=500), nullable=True, comment='縮圖 URL'),
    sa.Column('send_time', sa.DateTime(), nullable=True, comment='傳送時間'),
    sa.Column('send_count', sa.Integer(), nullable=True, comment='傳送人數'),
    sa.Column('open_count', sa.Integer(), nullable=True, comment='開啟次數（不重複）'),
    sa.Column('click_count', sa.Integer(), nullable=True, comment='點擊次數（不重複）'),
    sa.Column('send_status', sa.String(length=20), nullable=False, comment='發送狀態：排程發送/已發送/草稿/發送失敗'),
    sa.Column('failure_reason', sa.Text(), nullable=True, comment='發送失敗原因'),
    sa.Column('target_type', sa.String(length=20), nullable=False, comment='傳送對象類型：所有好友/篩選目標對象'),
    sa.Column('target_filter', sa.JSON(), nullable=True, comment='篩選條件（JSON格式）'),
    sa.Column('scheduled_date', sa.Date(), nullable=True, comment='排程發送日期'),
    sa.Column('scheduled_time', sa.Time(), nullable=True, comment='排程發送時間'),
    sa.Column('trigger_condition', sa.JSON(), nullable=True, comment='特定觸發條件'),
    sa.Column('estimated_send_count', sa.Integer(), nullable=True, comment='預計發送好友人數'),
    sa.Column('available_quota', sa.Integer(), nullable=True, comment='可用訊息配額用量'),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True, comment='關聯活動ID（選填）'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='創建者ID'),
    sa.Column('flex_message_json', sa.Text(), nullable=True, comment='Flex Message JSON 內容'),
    sa.Column('interaction_tags', sa.JSON(), nullable=True, comment='互動標籤（相容舊程式）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['message_templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_questions',
    sa.Column('survey_id', sa.BigInteger(), nullable=False, comment='問卷ID'),
    sa.Column('question_type', sa.Enum('NAME', 'PHONE', 'EMAIL', 'BIRTHDAY', 'ADDRESS', 'GENDER', 'ID_NUMBER', 'LINK', 'VIDEO', 'IMAGE', name='questiontype'), nullable=False, comment='題目類型'),
    sa.Column('question_text', sa.Text(), nullable=False, comment='題目文字'),
    sa.Column('font_size', sa.Integer(), nullable=True, comment='字型大小'),
    sa.Column('description', sa.Text(), nullable=True, comment='題目描述'),
    sa.Column('options', sa.JSON(), nullable=True, comment='選項'),
    sa.Column('is_required', sa.Boolean(), nullable=False, comment='是否必填'),
    sa.Column('min_length', sa.Integer(), nullable=True, comment='最小長度'),
    sa.Column('max_length', sa.Integer(), nullable=True, comment='最大長度'),
    sa.Column('min_value', sa.Integer(), nullable=True, comment='最小值'),
    sa.Column('max_value', sa.Integer(), nullable=True, comment='最大值'),
    sa.Column('order', sa.Integer(), nullable=False, comment='題目順序'),
    sa.Column('video_description', sa.Text(), nullable=True, comment='影片描述'),
    sa.Column('video_link', sa.String(length=500), nullable=True, comment='影片超連結'),
    sa.Column('image_description', sa.Text(), nullable=True, comment='圖片描述'),
    sa.Column('image_link', sa.String(length=500), nullable=True, comment='圖片連結（編輯使用）'),
    sa.Column('image_base64', sa.Text(), nullable=True, comment='圖片Base64（發送使用）'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主鍵ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='創建時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_questions_survey_id'), 'survey_questions', ['survey_id'], unique=False)
    op.create_table('survey_responses',
    sa.Column('survey_id', sa.BigInteger(), nullable=False, comment='問卷ID'),
    sa.Column('member_id', sa.BigInteger(), nullable=False, comment='會員ID'),
    sa.Column('answers', sa.JSON(), nullable=False, comment='答案'),
    sa.Column('is_completed', sa.Boolean(), nullable=False, comment='是否完成'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成時間'),
    sa.Column('source', sa.String(length=50), nullable=True, comment='來源'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='IP地址'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='用戶代理'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主鍵ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='創建時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_responses_member_id'), 'survey_responses', ['member_id'], unique=False)
    op.create_index(op.f('ix_survey_responses_survey_id'), 'survey_responses', ['survey_id'], unique=False)
    op.create_table('template_carousel_items',
    sa.Column('template_id', sa.BigInteger(), nullable=False, comment='模板ID'),
    sa.Column('image_url', sa.String(length=500), nullable=False, comment='圖片URL'),
    sa.Column('title', sa.String(length=100), nullable=True, comment='標題'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='描述'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True, comment='金額'),
    sa.Column('action_url', sa.String(length=500), nullable=True, comment='動作URL'),
    sa.Column('interaction_tag_id', sa.BigInteger(), nullable=True, comment='互動標籤ID'),
    sa.Column('action_button_text', sa.String(length=100), nullable=True, comment='動作按鈕文字'),
    sa.Column('action_button_enabled', sa.Boolean(), nullable=True, comment='動作按鈕啟用'),
    sa.Column('action_button_interaction_type', sa.String(length=50), nullable=True, comment='動作按鈕互動類型'),
    sa.Column('action_button_url', sa.String(length=500), nullable=True, comment='動作按鈕網址'),
    sa.Column('action_button_trigger_message', sa.Text(), nullable=True, comment='動作按鈕觸發訊息'),
    sa.Column('action_button_trigger_image_url', sa.String(length=500), nullable=True, comment='動作按鈕觸發圖片URL'),
    sa.Column('action_button2_text', sa.String(length=100), nullable=True, comment='第二個動作按鈕文字'),
    sa.Column('action_button2_enabled', sa.Boolean(), nullable=True, comment='第二個動作按鈕啟用'),
    sa.Column('action_button2_interaction_type', sa.String(length=50), nullable=True, comment='第二個動作按鈕互動類型'),
    sa.Column('action_button2_url', sa.String(length=500), nullable=True, comment='第二個動作按鈕網址'),
    sa.Column('action_button2_trigger_message', sa.Text(), nullable=True, comment='第二個動作按鈕觸發訊息'),
    sa.Column('action_button2_trigger_image_url', sa.String(length=500), nullable=True, comment='第二個動作按鈕觸發圖片URL'),
    sa.Column('image_aspect_ratio', sa.String(length=10), nullable=False, comment='圖片長寬比例'),
    sa.Column('image_click_action_type', sa.String(length=50), nullable=False, comment='圖片點擊動作類型'),
    sa.Column('image_click_action_value', sa.Text(), nullable=True, comment='圖片點擊動作值'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('click_count', sa.Integer(), nullable=True, comment='點擊次數'),
    sa.Column('unique_click_count', sa.Integer(), nullable=True, comment='唯一點擊次數'),
    sa.Column('last_clicked_at', sa.DateTime(), nullable=True, comment='最後點擊時間'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主鍵ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='創建時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.ForeignKeyConstraint(['interaction_tag_id'], ['interaction_tags.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['message_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_carousel_items_template_id'), 'template_carousel_items', ['template_id'], unique=False)
    op.create_table('auto_response_keywords',
    sa.Column('auto_response_id', sa.BigInteger(), nullable=False, comment='自動回應ID'),
    sa.Column('keyword', sa.String(length=50), nullable=False, comment='關鍵字'),
    sa.Column('match_count', sa.Integer(), nullable=True, comment='匹配次數'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主鍵ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='創建時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.ForeignKeyConstraint(['auto_response_id'], ['auto_responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auto_response_id', 'keyword', name='uq_auto_response_keyword')
    )
    op.create_index(op.f('ix_auto_response_keywords_auto_response_id'), 'auto_response_keywords', ['auto_response_id'], unique=False)
    op.create_table('component_interaction_logs',
    sa.Column('line_id', sa.String(length=100), nullable=False, comment='LINE 用戶 UID'),
    sa.Column('message_id', sa.BigInteger(), nullable=False, comment='群發訊息ID'),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True, comment='活動ID（選填）'),
    sa.Column('template_id', sa.BigInteger(), nullable=True, comment='模板ID'),
    sa.Column('carousel_item_id', sa.BigInteger(), nullable=True, comment='輪播圖卡片ID'),
    sa.Column('interaction_tag_id', sa.BigInteger(), nullable=True, comment='互動標籤ID'),
    sa.Column('component_slot', sa.String(length=50), nullable=True, comment='模板元件槽位'),
    sa.Column('interaction_type', sa.Enum('image_click', 'button_message', 'button_url', 'button_image', 'postback', name='interactiontype'), nullable=False, comment='互動類型'),
    sa.Column('interaction_value', sa.Text(), nullable=True, comment='互動值（如URL、訊息內容等）'),
    sa.Column('triggered_at', sa.DateTime(), nullable=False, comment='觸發時間'),
    sa.Column('line_event_type', sa.String(length=50), nullable=True, comment='LINE事件類型'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='用戶代理'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主鍵ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='創建時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['carousel_item_id'], ['template_carousel_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['interaction_tag_id'], ['interaction_tags.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['message_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_component_interaction_logs_campaign_id'), 'component_interaction_logs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_component_interaction_logs_carousel_item_id'), 'component_interaction_logs', ['carousel_item_id'], unique=False)
    op.create_index(op.f('ix_component_interaction_logs_component_slot'), 'component_interaction_logs', ['component_slot'], unique=False)
    op.create_index(op.f('ix_component_interaction_logs_interaction_tag_id'), 'component_interaction_logs', ['interaction_tag_id'], unique=False)
    op.create_index(op.f('ix_component_interaction_logs_interaction_type'), 'component_interaction_logs', ['interaction_type'], unique=False)
    op.create_index(op.f('ix_component_interaction_logs_line_id'), 'component_interaction_logs', ['line_id'], unique=False)
    op.create_index(op.f('ix_component_interaction_logs_message_id'), 'component_interaction_logs', ['message_id'], unique=False)
    op.create_index(op.f('ix_component_interaction_logs_template_id'), 'component_interaction_logs', ['template_id'], unique=False)
    op.create_index(op.f('ix_component_interaction_logs_triggered_at'), 'component_interaction_logs', ['triggered_at'], unique=False)
    op.create_table('member_interaction_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False, comment='所屬會員ID'),
    sa.Column('tag_id', sa.BigInteger(), nullable=False, comment='互動標籤ID'),
    sa.Column('message_id', sa.BigInteger(), nullable=True, comment='關聯的訊息ID（若來自訊息模板）'),
    sa.Column('triggered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='觸發時間'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['interaction_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'tag_id', 'message_id', name='uq_member_tag_msg_interaction')
    )
    op.create_index(op.f('ix_member_interaction_records_member_id'), 'member_interaction_records', ['member_id'], unique=False)
    op.create_index(op.f('ix_member_interaction_records_message_id'), 'member_interaction_records', ['message_id'], unique=False)
    op.create_index(op.f('ix_member_interaction_records_tag_id'), 'member_interaction_records', ['tag_id'], unique=False)
    op.create_table('member_tags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False, comment='所屬會員ID'),
    sa.Column('tag_name', sa.String(length=20), nullable=False, comment='標籤名稱'),
    sa.Column('tag_source', sa.String(length=20), nullable=True, comment='標籤來源：CRM/PMS/問券/後台自訂'),
    sa.Column('trigger_count', sa.Integer(), nullable=True, comment='觸發次數'),
    sa.Column('trigger_member_count', sa.Integer(), nullable=True, comment='觸發會員數'),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True, comment='最近觸發時間'),
    sa.Column('message_id', sa.BigInteger(), nullable=True, comment='觸發來源訊息ID（用於去重）'),
    sa.Column('tagged_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='標記時間'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'tag_name', 'message_id', name='uq_member_tag_message')
    )
    op.create_index(op.f('ix_member_tags_member_id'), 'member_tags', ['member_id'], unique=False)
    op.create_index(op.f('ix_member_tags_message_id'), 'member_tags', ['message_id'], unique=False)
    op.create_table('message_recipients',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False, comment='群發訊息ID'),
    sa.Column('member_id', sa.BigInteger(), nullable=False, comment='會員ID'),
    sa.Column('sent_at', sa.DateTime(), nullable=True, comment='發送時間'),
    sa.Column('opened_at', sa.DateTime(), nullable=True, comment='開啟時間'),
    sa.Column('clicked_at', sa.DateTime(), nullable=True, comment='點擊時間'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='狀態：pending/sent/opened/clicked/failed'),
    sa.Column('error_message', sa.String(length=500), nullable=True, comment='錯誤訊息'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'member_id', name='uq_message_member')
    )
    op.create_index(op.f('ix_message_recipients_member_id'), 'message_recipients', ['member_id'], unique=False)
    op.create_index(op.f('ix_message_recipients_message_id'), 'message_recipients', ['message_id'], unique=False)
    op.create_table('message_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False, comment='所屬會員ID'),
    sa.Column('message_content', sa.Text(), nullable=False, comment='訊息內容'),
    sa.Column('message_type', sa.String(length=20), nullable=False, comment='訊息類型：純文字/圖片/訊息模板'),
    sa.Column('message_status', sa.String(length=20), nullable=True, comment='訊息狀態：已讀/未讀'),
    sa.Column('send_time', sa.Time(), nullable=True, comment='傳送時間（HH:MM）'),
    sa.Column('message_source', sa.String(length=50), nullable=True, comment='訊息來源：人工回覆/訊息推播/自動回應'),
    sa.Column('conversation_date', sa.Date(), nullable=True, comment='對話開啟日期'),
    sa.Column('scheduled_send', sa.Boolean(), nullable=True, comment='是否排程發送'),
    sa.Column('scheduled_date', sa.Date(), nullable=True, comment='排程指定日期'),
    sa.Column('scheduled_time', sa.Time(), nullable=True, comment='排程指定時間'),
    sa.Column('direction', sa.String(length=20), nullable=True, comment='方向：incoming/outgoing'),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True, comment='來源群發訊息ID（相容）'),
    sa.Column('sender_type', sa.String(length=20), nullable=True, comment='發送者類型（相容）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.ForeignKeyConstraint(['campaign_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_records_member_id'), 'message_records', ['member_id'], unique=False)
    op.create_table('tag_trigger_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False, comment='會員ID'),
    sa.Column('tag_id', sa.BigInteger(), nullable=False, comment='標籤ID'),
    sa.Column('message_id', sa.BigInteger(), nullable=True, comment='群發訊息ID'),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True, comment='活動ID（選填）'),
    sa.Column('trigger_source', sa.Enum('CLICK', 'INTERACTION', 'MANUAL', name='triggersource'), nullable=False, comment='觸發來源'),
    sa.Column('triggered_at', sa.DateTime(), nullable=False, comment='觸發時間'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='創建時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['interaction_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_trigger_logs_campaign_id'), 'tag_trigger_logs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_tag_trigger_logs_member_id'), 'tag_trigger_logs', ['member_id'], unique=False)
    op.create_index(op.f('ix_tag_trigger_logs_message_id'), 'tag_trigger_logs', ['message_id'], unique=False)
    op.create_index(op.f('ix_tag_trigger_logs_tag_id'), 'tag_trigger_logs', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_trigger_logs_tag_id'), table_name='tag_trigger_logs')
    op.drop_index(op.f('ix_tag_trigger_logs_message_id'), table_name='tag_trigger_logs')
    op.drop_index(op.f('ix_tag_trigger_logs_member_id'), table_name='tag_trigger_logs')
    op.drop_index(op.f('ix_tag_trigger_logs_campaign_id'), table_name='tag_trigger_logs')
    op.drop_table('tag_trigger_logs')
    op.drop_index(op.f('ix_message_records_member_id'), table_name='message_records')
    op.drop_table('message_records')
    op.drop_index(op.f('ix_message_recipients_message_id'), table_name='message_recipients')
    op.drop_index(op.f('ix_message_recipients_member_id'), table_name='message_recipients')
    op.drop_table('message_recipients')
    op.drop_index(op.f('ix_member_tags_message_id'), table_name='member_tags')
    op.drop_index(op.f('ix_member_tags_member_id'), table_name='member_tags')
    op.drop_table('member_tags')
    op.drop_index(op.f('ix_member_interaction_records_tag_id'), table_name='member_interaction_records')
    op.drop_index(op.f('ix_member_interaction_records_message_id'), table_name='member_interaction_records')
    op.drop_index(op.f('ix_member_interaction_records_member_id'), table_name='member_interaction_records')
    op.drop_table('member_interaction_records')
    op.drop_index(op.f('ix_component_interaction_logs_triggered_at'), table_name='component_interaction_logs')
    op.drop_index(op.f('ix_component_interaction_logs_template_id'), table_name='component_interaction_logs')
    op.drop_index(op.f('ix_component_interaction_logs_message_id'), table_name='component_interaction_logs')
    op.drop_index(op.f('ix_component_interaction_logs_line_id'), table_name='component_interaction_logs')
    op.drop_index(op.f('ix_component_interaction_logs_interaction_type'), table_name='component_interaction_logs')
    op.drop_index(op.f('ix_component_interaction_logs_interaction_tag_id'), table_name='component_interaction_logs')
    op.drop_index(op.f('ix_component_interaction_logs_component_slot'), table_name='component_interaction_logs')
    op.drop_index(op.f('ix_component_interaction_logs_carousel_item_id'), table_name='component_interaction_logs')
    op.drop_index(op.f('ix_component_interaction_logs_campaign_id'), table_name='component_interaction_logs')
    op.drop_table('component_interaction_logs')
    op.drop_index(op.f('ix_auto_response_keywords_auto_response_id'), table_name='auto_response_keywords')
    op.drop_table('auto_response_keywords')
    op.drop_index(op.f('ix_template_carousel_items_template_id'), table_name='template_carousel_items')
    op.drop_table('template_carousel_items')
    op.drop_index(op.f('ix_survey_responses_survey_id'), table_name='survey_responses')
    op.drop_index(op.f('ix_survey_responses_member_id'), table_name='survey_responses')
    op.drop_table('survey_responses')
    op.drop_index(op.f('ix_survey_questions_survey_id'), table_name='survey_questions')
    op.drop_table('survey_questions')
    op.drop_table('messages')
    op.drop_index(op.f('ix_consumption_records_member_id'), table_name='consumption_records')
    op.drop_table('consumption_records')
    op.drop_table('auto_responses')
    op.drop_table('surveys')
    op.drop_index(op.f('ix_pms_integrations_phone'), table_name='pms_integrations')
    op.drop_index(op.f('ix_pms_integrations_member_id'), table_name='pms_integrations')
    op.drop_index(op.f('ix_pms_integrations_id_number'), table_name='pms_integrations')
    op.drop_table('pms_integrations')
    op.drop_table('message_templates')
    op.drop_table('users')
    op.drop_table('survey_templates')
    op.drop_index(op.f('ix_ryan_click_demo_source_campaign_id'), table_name='ryan_click_demo')
    op.drop_table('ryan_click_demo')
    op.drop_index(op.f('ix_members_phone'), table_name='members')
    op.drop_index(op.f('ix_members_line_uid'), table_name='members')
    op.drop_index(op.f('ix_members_id_number'), table_name='members')
    op.drop_index(op.f('ix_members_email'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_interaction_tags_tag_name'), table_name='interaction_tags')
    op.drop_table('interaction_tags')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
