"""add_new_tables_from_spec_v0_2

Revision ID: 25ed166f31de
Revises: 3219a710931c
Create Date: 2025-11-13 10:46:01.213734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25ed166f31de'
down_revision: Union[str, None] = '3219a710931c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False, comment='登入信箱，作為識別帳號'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密碼雜湊值（使用 bcrypt/Argon2 加密儲存）'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='管理員名稱'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('permission_name', sa.String(length=100), nullable=False, comment='權限名稱，如「查看會員資料」「發送群發訊息」'),
    sa.Column('permission_code', sa.String(length=100), nullable=False, comment='權限代碼，如「member.view」「message.send」'),
    sa.Column('resource', sa.String(length=50), nullable=True, comment='資源類別，如「member」「message」「tag」'),
    sa.Column('action', sa.String(length=50), nullable=True, comment='操作類型，如「view」「create」「update」'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='權限描述'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permission_code'),
    sa.UniqueConstraint('permission_name')
    )
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False, comment='角色名稱，如「超級管理員」「管理員」「一般員工」'),
    sa.Column('role_code', sa.String(length=50), nullable=False, comment='角色代碼，如「superadmin」「admin」「staff」'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='角色描述'),
    sa.Column('is_system_role', sa.Boolean(), nullable=False, comment='是否為系統預設角色'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_code'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('tag_rules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tag_name', sa.String(length=20), nullable=False, comment='標籤名稱（如：高消費客戶、常客）'),
    sa.Column('tag_source', sa.String(length=20), nullable=False, comment='標籤來源：CRM/PMS'),
    sa.Column('rule_type', sa.String(length=50), nullable=False, comment='規則類型：consumption_amount（消費金額）/visit_frequency（訪問頻率）/interaction_time（互動時間）/room_type（房型分類）'),
    sa.Column('threshold_value', sa.Float(), nullable=True, comment='門檻值（如：30000 元、3 次）'),
    sa.Column('threshold_unit', sa.String(length=20), nullable=True, comment='單位：NTD（新台幣）/times（次）/days（天）'),
    sa.Column('period_days', sa.Integer(), nullable=True, comment='計算週期（天數），如 365 表示滾動 12 個月'),
    sa.Column('condition_operator', sa.String(length=10), nullable=False, comment='比較運算子：>=/>/<=/<='),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='是否啟用'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False, comment='管理員 ID'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色 ID'),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='指派時間'),
    sa.Column('assigned_by', sa.BigInteger(), nullable=True, comment='指派人（管理員 ID）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='創建時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_id', 'role_id', name='uq_admin_role')
    )
    op.create_table('line_oa_configs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False, comment='所屬管理員'),
    sa.Column('channel_id', sa.String(length=20), nullable=True, comment='Messaging API Channel ID（10位數字）'),
    sa.Column('channel_secret', sa.String(length=50), nullable=True, comment='Messaging API Channel Secret（32字元英數字）'),
    sa.Column('channel_access_token', sa.String(length=255), nullable=True, comment='Messaging API Channel Access Token'),
    sa.Column('line_account_id', sa.String(length=50), nullable=True, comment='LINE 官方帳號 ID，如 @262qaash'),
    sa.Column('webhook_enabled', sa.Boolean(), nullable=True, comment='Webhook 是否已開啟'),
    sa.Column('is_verified', sa.Boolean(), nullable=True, comment='是否已完成 LINE 驗證'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='最後更新時間'),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_configs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False, comment='所屬管理員'),
    sa.Column('channel_id', sa.String(length=20), nullable=True, comment='Login Channel ID（以165開頭的10位數字）'),
    sa.Column('channel_secret', sa.String(length=50), nullable=True, comment='Login Channel Secret（32位大小寫英數字）'),
    sa.Column('is_verified', sa.Boolean(), nullable=True, comment='是否已完成 LINE 驗證'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='最後更新時間'),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False, comment='所屬管理員'),
    sa.Column('login_method', sa.String(length=20), nullable=True, comment='登入方式：email_password / google / line'),
    sa.Column('login_time', sa.DateTime(), nullable=False, comment='登入時間（UTC+8 時區）'),
    sa.Column('expire_time', sa.DateTime(), nullable=True, comment='會話過期時間'),
    sa.Column('device_info', sa.Text(), nullable=True, comment='裝置資訊'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='會話是否有效'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色 ID'),
    sa.Column('permission_id', sa.BigInteger(), nullable=False, comment='權限 ID'),
    sa.Column('granted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='授予時間'),
    sa.Column('granted_by', sa.BigInteger(), nullable=True, comment='授予人（管理員 ID）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='創建時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_table('system_authorizations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False, comment='所屬管理員'),
    sa.Column('expire_date', sa.Date(), nullable=False, comment='授權到期日'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='授權是否有效'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auto_response_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('response_id', sa.BigInteger(), nullable=False, comment='所屬自動回應'),
    sa.Column('message_content', sa.Text(), nullable=False, comment='訊息內容（純文字），建議 <= 500 字元'),
    sa.Column('sequence_order', sa.Integer(), nullable=False, comment='UI 顯示順序與發送順序，>= 1'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.ForeignKeyConstraint(['response_id'], ['auto_responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_id', 'sequence_order', name='uq_response_sequence')
    )
    op.create_index(op.f('ix_auto_response_messages_response_id'), 'auto_response_messages', ['response_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auto_response_messages_response_id'), table_name='auto_response_messages')
    op.drop_table('auto_response_messages')
    op.drop_table('system_authorizations')
    op.drop_table('role_permissions')
    op.drop_table('login_sessions')
    op.drop_table('login_configs')
    op.drop_table('line_oa_configs')
    op.drop_table('admin_roles')
    op.drop_table('tag_rules')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('admins')
    # ### end Alembic commands ###
