"""add_interaction_tag_to_campaigns

Revision ID: 4eb09c2a7fbf
Revises: 
Create Date: 2025-10-09 08:07:28.212131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb09c2a7fbf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('interaction_tag', sa.String(length=50), nullable=True, comment='互動標籤'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'interaction_tag')
    # ### end Alembic commands ###
