"""add_survey_tables

Revision ID: a696d3d03a32
Revises: 4eb09c2a7fbf
Create Date: 2025-10-15 11:25:09.177998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a696d3d03a32'
down_revision: Union[str, None] = '4eb09c2a7fbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_templates',
    sa.Column('name', sa.String(length=100), nullable=False, comment='範本名稱'),
    sa.Column('description', sa.Text(), nullable=True, comment='範本描述'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='範本圖標'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='範本類別'),
    sa.Column('default_questions', sa.JSON(), nullable=True, comment='預設題目'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否啟用'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主鍵ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='創建時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surveys',
    sa.Column('name', sa.String(length=200), nullable=False, comment='問卷名稱'),
    sa.Column('template_id', sa.BigInteger(), nullable=False, comment='範本ID'),
    sa.Column('description', sa.Text(), nullable=True, comment='問卷描述'),
    sa.Column('target_audience', sa.Enum('ALL', 'FILTERED', name='targetaudience'), nullable=False, comment='目標受眾'),
    sa.Column('target_tags', sa.JSON(), nullable=True, comment='目標標籤'),
    sa.Column('schedule_type', sa.Enum('IMMEDIATE', 'SCHEDULED', name='scheduletype'), nullable=False, comment='排程類型'),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True, comment='排程時間'),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='surveystatus'), nullable=False, comment='狀態'),
    sa.Column('response_count', sa.Integer(), nullable=True, comment='回應數'),
    sa.Column('view_count', sa.Integer(), nullable=True, comment='瀏覽數'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='創建者ID'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主鍵ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='創建時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['survey_templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_questions',
    sa.Column('survey_id', sa.BigInteger(), nullable=False, comment='問卷ID'),
    sa.Column('question_type', sa.Enum('NAME', 'PHONE', 'EMAIL', 'BIRTHDAY', 'ADDRESS', 'GENDER', 'ID_NUMBER', 'LINK', 'VIDEO', 'IMAGE', name='questiontype'), nullable=False, comment='題目類型'),
    sa.Column('question_text', sa.Text(), nullable=False, comment='題目文字'),
    sa.Column('font_size', sa.Integer(), nullable=True, comment='字型大小'),
    sa.Column('description', sa.Text(), nullable=True, comment='題目描述'),
    sa.Column('options', sa.JSON(), nullable=True, comment='選項'),
    sa.Column('is_required', sa.Boolean(), nullable=False, comment='是否必填'),
    sa.Column('min_length', sa.Integer(), nullable=True, comment='最小長度'),
    sa.Column('max_length', sa.Integer(), nullable=True, comment='最大長度'),
    sa.Column('min_value', sa.Integer(), nullable=True, comment='最小值'),
    sa.Column('max_value', sa.Integer(), nullable=True, comment='最大值'),
    sa.Column('order', sa.Integer(), nullable=False, comment='題目順序'),
    sa.Column('video_description', sa.Text(), nullable=True, comment='影片描述'),
    sa.Column('video_link', sa.String(length=500), nullable=True, comment='影片超連結'),
    sa.Column('image_description', sa.Text(), nullable=True, comment='圖片描述'),
    sa.Column('image_link', sa.String(length=500), nullable=True, comment='圖片超連結'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主鍵ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='創建時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_questions_survey_id'), 'survey_questions', ['survey_id'], unique=False)
    op.create_table('survey_responses',
    sa.Column('survey_id', sa.BigInteger(), nullable=False, comment='問卷ID'),
    sa.Column('member_id', sa.BigInteger(), nullable=False, comment='會員ID'),
    sa.Column('answers', sa.JSON(), nullable=False, comment='答案'),
    sa.Column('is_completed', sa.Boolean(), nullable=False, comment='是否完成'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成時間'),
    sa.Column('source', sa.String(length=50), nullable=True, comment='來源'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='IP地址'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='用戶代理'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主鍵ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='創建時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_responses_member_id'), 'survey_responses', ['member_id'], unique=False)
    op.create_index(op.f('ix_survey_responses_survey_id'), 'survey_responses', ['survey_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_survey_responses_survey_id'), table_name='survey_responses')
    op.drop_index(op.f('ix_survey_responses_member_id'), table_name='survey_responses')
    op.drop_table('survey_responses')
    op.drop_index(op.f('ix_survey_questions_survey_id'), table_name='survey_questions')
    op.drop_table('survey_questions')
    op.drop_table('surveys')
    op.drop_table('survey_templates')
    # ### end Alembic commands ###
